site_name: Nome Projeto
repo_url: https://github.com/<usuario_github>/nome_projeto
repo_name: <usuario_github>/nome_projeto
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo claro

extra:
  generator: true
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<nome_usuario>
    - icon: fontawesome/brands/github
      link: https://github.com/<nome_usuario>

watch:
  - src/nome_projeto

plugins:
  - search:
      lang: pt-BR
  - mkdocstrings:
      handlers:
        python:
          paths: [ src/nome_projeto ]
          options:
            separate_signature: true
            show_signature_annotations: true
